baseURL = 'https://loquacious-mandazi-92bae5.netlify.app/'
languageCode = 'en-us'
title = 'CUDE'


paginate = 8

[params]
  description = "The CUDE fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"
 
