baseURL = 'https://cudu.netlify.app/'
languageCode = 'en-us'
title = 'CUDE'


paginate = 8

[params]
  description = "The CUDE fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"
[[menu.main]]
  name = "Disclaimer"
  url = "/disclaimer/"
  weight = 5
