baseURL = 'https://loquacious-mandazi-92bae5.netlify.app/'
languageCode = 'en-us'
title = 'Schritte Blog'

paginate = 4

[params]
  description = "The Schritte fastest blog"
  dateFormat = "Jan 2, 2006"

[taxonomies]
  category = "categories"
  author = "authors"
 
